# Generated by Django 5.2.1 on 2025-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
