# Generated by Django 5.2.1 on 2025-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_remove_activity_ad_priority_remove_event_ad_priority'),
        ('users', '0005_user_first_ip_user_second_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_data_consent',
            field=models.BooleanField(default=False, verbose_name='Consentement pour les données'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='activities.category', verbose_name='interests'),
        ),
    ]
