# Generated by Django 5.2.1 on 2025-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
