# Generated by Django 5.2.1 on 2025-06-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_category_description_en_category_description_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
