# Generated by Django 5.2.1 on 2025-06-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_promotion_end_date_alter_promotion_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_es',
            new_name='name_es',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_fr',
            new_name='name_fr',
        ),
    ]
