# Generated by Django 5.2.1 on 2025-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_title_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
