# Generated by Django 5.2.1 on 2025-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
