# Generated by Django 5.2.1 on 2025-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_place_id_event_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ad_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='ad_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_national',
            field=models.BooleanField(default=False),
        ),
    ]
