# Generated by Django 5.2.1 on 2025-07-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_remove_activity_ad_priority_remove_event_ad_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
