# Generated by Django 5.2.1 on 2025-07-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activity_average_rating_event_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='average_rating',
        ),
    ]
