# Generated by Django 5.2.1 on 2025-07-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_remove_activity_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
