# Generated by Django 5.2.1 on 2025-08-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_activity_average_rating_event_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Category for markers in flutter UI etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_activities', to='activities.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Category for markers in flutter UI etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_events', to='activities.category'),
        ),
    ]
