# Generated by Django 5.2.1 on 2025-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_activity_primary_category_event_primary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_by_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='has_updated_dates',
            field=models.BooleanField(default=True),
        ),
    ]
