# Generated by Django 5.2.1 on 2025-09-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_activity_is_by_reservation_event_has_updated_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_by_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(condition=models.Q(('is_active', True), ('latitude__isnull', False), ('longitude__isnull', False)), fields=['latitude', 'longitude'], name='act_lat_lon_active_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('is_public', True), ('latitude__isnull', False), ('longitude__isnull', False)), fields=['latitude', 'longitude'], name='evt_lat_lon_public_idx'),
        ),
    ]
