# Generated by Django 5.2.1 on 2025-12-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_event_is_by_reservation_alter_activity_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tips',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tips',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
