# Generated by Django 5.2.1 on 2025-06-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_priorityad_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='format',
            field=models.CharField(choices=[('native', 'Native Ad'), ('banner', 'Banner'), ('interstitial', 'Interstitial'), ('push', 'Push Notification'), ('proximity', 'Proximity Ad'), ('video_interstitial', 'Video Interstitial')], default='native', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
