# Generated by Django 5.2.1 on 2025-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_adinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinvoice',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wire_transfer', 'Wire Transfer'), ('credit_card', 'Credit Card'), ('check', 'Check'), ('paypal', 'PayPal')], max_length=50),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
