# Generated by Django 5.2.1 on 2025-06-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_adinvoice_currency_adinvoice_notes_adinvoice_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='cpa_price',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='cpc_price',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='cpm_price',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='forfait_price',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contract_signed_date',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contract_type',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reference', models.CharField(max_length=50, unique=True)),
                ('campaign_type', models.CharField(choices=[('CPM', 'CPM'), ('CPC', 'CPC'), ('CPA', 'CPA'), ('FORFAIT', 'Forfait'), ('PACK', 'Pack Premium')], max_length=20)),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField()),
                ('signed_date', models.DateField()),
                ('forfait_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ads.partner')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='ads.contract'),
        ),
    ]
