# Generated by Django 5.2.1 on 2025-06-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_advertisement_cpa_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cpa_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpc_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='forfait_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
