# Generated by Django 5.2.1 on 2025-07-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_contract_cpa_price_contract_cpc_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adinvoice',
            name='partner',
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='ads.advertisement'),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
