# Generated by Django 5.2.1 on 2025-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_adinvoice_advertisement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinvoice',
            name='period_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='period_conversions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adinvoice',
            name='period_impressions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
