# Generated by Django 5.2.1 on 2025-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_adinvoice_period_clicks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinvoice',
            name='total_excluding_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
