# Generated by Django 5.2.1 on 2025-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_adinvoice_total_excluding_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
