# Generated by Django 5.2.1 on 2025-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_partner_city_partner_country_partner_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='forfait_price',
            new_name='package_price',
        ),
        migrations.AddField(
            model_name='contract',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='campaign_type',
            field=models.CharField(choices=[('CPM', 'CPM'), ('CPC', 'CPC'), ('CPA', 'CPA'), ('COMBO', 'Combo'), ('PACKAGE', 'Package'), ('PREMIUM', 'Pack Premium')], max_length=20),
        ),
    ]
