# Generated by Django 5.2.1 on 2025-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_rename_forfait_price_contract_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
