# Generated by Django 5.2.1 on 2025-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_advertisement_tax_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personne de contact principale'),
        ),
        migrations.AddField(
            model_name='partner',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom légal (si différent)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'identification fiscale (EIN/Tax ID)"),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
    ]
