# Generated by Django 5.2.1 on 2025-07-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_remove_activity_ad_priority_remove_event_ad_priority'),
        ('ads', '0018_alter_partner_options_partner_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at'], 'verbose_name': 'campagne Publicitaire (Ios)', 'verbose_name_plural': 'Campagnes Publicitaires (Ios)'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrat Cadre', 'verbose_name_plural': 'Contrats Cadres'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cpa_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cpc_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cpm_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='package_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='premium_price',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_creative_content_text',
            field=models.TextField(blank=True, help_text="Texte principal ou description de l'annonce.", null=True, verbose_name="Contenu Textuel de l'Annonce"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_placement_details',
            field=models.TextField(blank=True, help_text="Emplacements spécifiques dans l'application (ex: 'Bannière en haut des pages de ville').", null=True, verbose_name="Placement de l'Annonce/ad_placement_details"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='campaign_type',
            field=models.CharField(choices=[('CPM', 'CPM'), ('CPC', 'CPC'), ('CPA', 'CPA'), ('COMBO', 'Combo'), ('PACKAGE', 'Package'), ('PREMIUM', 'Pack Premium')], default='COMBO', max_length=20, verbose_name='Type de Campagne/campaign_type'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cpa_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Taux CPA/cpa_price'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cpc_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Taux CPC/cpc_price'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cpm_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Taux CPM/cpm_price'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Devise/currency'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='io_reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence commande/io_reference_number'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='make_good_details',
            field=models.TextField(blank=True, help_text='Description des actions de compensation (ex: prolongation de campagne, crédit).', null=True, verbose_name='Détails de Compensation/make_good_details'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='make_good_status',
            field=models.CharField(choices=[('NONE', 'No Make-Good Required'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved for Make-Good'), ('DELIVERED', 'Make-Good Delivered'), ('REJECTED', 'Make-Good Rejected'), ('COMPLETED', 'Make-Good Completed'), ('PARTIAL', 'Partial Make-Good Delivered')], default='NONE', max_length=20, verbose_name='Statut de Compensation/Make-Good status'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix Forfait/package_price'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='performance_goal_clicks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Objectif Clics/performance_goal_clicks'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='performance_goal_conversions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Objectif Conversions/performance_goal_conversions'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='performance_goal_impressions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Objectif Impressions/performance_goal_impressions'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix Pack Premium/premium_price'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='reporting_format',
            field=models.CharField(choices=[('PDF', 'pdf'), ('CSV', 'csv'), ('XLSX', 'xlsx')], default='PDF', max_length=30, verbose_name='Format de Rapports/reporting_format'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='reporting_frequency',
            field=models.CharField(choices=[('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly'), ('QUARTERLY', 'quarterly'), ('YEARLY', 'yearly'), ('PER_CAMPAIGN', 'per_campaign'), ('ON_DEMAND', 'on_demand'), ('AUTOMATED_DASHBOARD', 'automated_dashboard')], default='MONTHLY', help_text='Fréquence à laquelle les rapports de performance seront générés.', max_length=20, verbose_name='Fréquence de Rapports/reporting_frequency'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled'), ('EXPIRED', 'expired'), ('SUSPENDED', 'suspended'), ('FAILED', 'failed')], default='PENDING', max_length=20, verbose_name='Statut Annonce/Advertisement status'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_audience_description',
            field=models.TextField(blank=True, help_text='Détails sur le ciblage démographique, géographique, comportemental, etc.', null=True, verbose_name='Public Cible/target_audience_description'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='total_agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix total fixe pour l'estimation de les campagnes à la performance.", max_digits=10, null=True, verbose_name='Prix Total Convenu/total_agreed_price'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='contract',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Renouvellement Automatique'),
        ),
        migrations.AddField(
            model_name='contract',
            name='data_processing_agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/dpa_agreements/', verbose_name='Fichier DPA (TDPSA)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='data_processing_agreement_required',
            field=models.BooleanField(default=False, help_text='Indique si un Accord de Traitement des Données est requis pour ce partenaire en vertu de la TDPSA.', verbose_name='DPA Requis (TDPSA)/data_processing_agreement_required'),
        ),
        migrations.AddField(
            model_name='contract',
            name='dispute_resolution_method',
            field=models.CharField(choices=[('NONE', 'No dispute'), ('NEGOTIATION', 'Negotiation'), ('MEDIATION', 'Mediation'), ('ARBITRATION', 'Arbitration'), ('LITIGATION', 'Litigation (Court)'), ('MEDIATION_ARBITRATION', 'Mediation then Arbitration')], default='MEDIATION', max_length=25, verbose_name='Méthode Résolution des Litiges/dispute_resolution_method'),
        ),
        migrations.AddField(
            model_name='contract',
            name='governing_law',
            field=models.CharField(choices=[('TX', 'Texas Law'), ('US_FEDERAL', 'U.S. Federal Law'), ('OTHER', 'Other (Specify in details)')], default='TX', help_text="Le droit applicable pour ce contrat. Par défaut, c'est le droit du Texas (Texas Law).", max_length=10, verbose_name='Droit Applicable/governing_law'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pricing_terms_description',
            field=models.TextField(blank=True, help_text="Décrit comment les tarifs sont déterminés pour les différents types de campagnes (ex: 'Tarifs spécifiés dans les Bons de Commande individuels').", null=True, verbose_name='Description Générale des Termes de Tarification/pricing_terms_description'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_period_months',
            field=models.PositiveIntegerField(blank=True, help_text='Applicable si le renouvellement automatique est activé.', null=True, verbose_name='Période de Renouvellement(en mois)/renewal_period_months'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_contract_file',
            field=models.FileField(blank=True, help_text='Téléchargez le fichier PDF du contrat signé. Ce fichier doit être signé par les deux parties.', null=True, upload_to='contracts/signed_agreements/', verbose_name='Fichier du Contrat Signé(PDF)/signed_contract_file(PDF)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Résiliation/termination_date'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison de la Résiliation/termination_reason'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification/updated_at'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de Clics/clicks_count'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='ads.contract', verbose_name='Contrat Cadre/contract'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='conversions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de Conversions/conversions_count'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(verbose_name='Fin de Campagne/end_date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='format',
            field=models.CharField(choices=[('native', 'Native Ad'), ('banner', 'Banner'), ('interstitial', 'Interstitial'), ('push', 'Push Notification'), ('proximity', 'Proximity Ad'), ('video_interstitial', 'Video Interstitial')], default='native', max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name="Image de l'Annonce/image"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'Impressions/impressions_count"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link_url',
            field=models.URLField(help_text="URL vers laquelle l'annonce redirige les utilisateurs lorsqu'ils cliquent.", verbose_name='URL de Destination (Clic)/link_url'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='related_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='activities.activity', verbose_name='Activité Liée/related_activity'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='activities.event', verbose_name='Événement Lié/related_event'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(verbose_name='Début de Campagne/start_date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de Taxe (%)/tax_rate'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Titre de l'Annonce/title"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/', verbose_name="Fichier Vidéo de l'Annonce/video"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL Vidéo de l'Annonce/video_url"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='Référence du Contrat'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration_months',
            field=models.PositiveIntegerField(verbose_name='Durée (en mois)/duration_months'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Contrat Actif'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ads.partner', verbose_name='Partenaire'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(help_text='Date à laquelle le contrat a été signé par les deux parties.', verbose_name='Date de Signature/Signed_Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Début du Contrat/Contract start_date'),
        ),
    ]
