# Generated by Django 5.2.1 on 2025-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_alter_advertisement_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at'], 'verbose_name': 'campagne Publicitaire/IOs', 'verbose_name_plural': 'Campagnes Publicitaires (Ios)'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière modification/updated_at'),
        ),
    ]
