# Generated by Django 5.2.1 on 2025-07-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrat Cadre/contract', 'verbose_name_plural': 'Contrats Cadres'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partenaire/partner', 'verbose_name_plural': 'Partenaires'},
        ),
    ]
