# Generated by Django 5.2.1 on 2025-07-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_alter_contract_options_alter_partner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adinvoice',
            options={'verbose_name': 'facture/invoice'},
        ),
    ]
