# Generated by Django 5.2.1 on 2025-07-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_alter_adinvoice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adinvoice',
            name='currency',
        ),
    ]
