# Generated by Django 5.2.1 on 2025-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_remove_adinvoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
