# Generated by Django 5.2.1 on 2025-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_alter_partner_legal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="EIN/Tax ID(Numéro d'identification fiscale)"),
        ),
    ]
