# Generated by Django 5.2.1 on 2025-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_alter_partner_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partenaire/partner', 'verbose_name_plural': 'Partenaires/partners'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
