# Generated by Django 5.2.1 on 2025-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_alter_partner_options_alter_partner_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='legal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
