# Generated by Django 5.2.1 on 2025-07-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0027_alter_partner_legal_name_alter_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='Référence du Contrat/contract reference'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dispute_resolution_method',
            field=models.CharField(choices=[('NONE', 'No dispute'), ('NEGOTIATION', 'Negotiation'), ('MEDIATION', 'Mediation'), ('ARBITRATION', 'Arbitration'), ('LITIGATION', 'Litigation (Court)'), ('MEDIATION_ARBITRATION', 'Mediation then Arbitration')], default='NONE', max_length=25, verbose_name='Méthode Résolution des Litiges/dispute_resolution_method'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='state',
            field=models.CharField(blank=True, default='TEXAS', max_length=100),
        ),
    ]
