# Generated by Django 5.2.1 on 2025-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_alter_contract_contract_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True, help_text='Informations supplémentaires ou historiques sur ce partenaire.', null=True, verbose_name='Notes Internes / Internal Partner Notes'),
        ),
    ]
