# Generated by Django 5.2.1 on 2025-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_partner_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pricing_terms_description',
            field=models.TextField(blank=True, default='Rates specified in individual Insertion Orders(advertisements)', help_text="Décrit comment les tarifs sont déterminés pour les différents types de campagnes (ex: 'Tarifs spécifiés dans les Bons de Commande individuels').", null=True, verbose_name='Description Générale des Termes de Tarification/pricing_terms_description'),
        ),
    ]
