# Generated by Django 5.2.1 on 2025-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0030_alter_contract_pricing_terms_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='push_message',
            field=models.CharField(blank=True, help_text='Texte court et percutant pour la notification push.', max_length=255, null=True, verbose_name='Message de la notification Push'),
        ),
    ]
