# Generated by Django 5.2.1 on 2025-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_advertisement_push_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='score_bonus',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
