# Generated by Django 5.2.1 on 2025-07-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_advertisement_score_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityAd',
        ),
    ]
