# Generated by Django 5.2.1 on 2025-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_delete_priorityad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='score_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
