# Generated by Django 5.2.1 on 2025-07-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0034_alter_advertisement_score_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_creative_content_text_en',
            field=models.TextField(blank=True, help_text="Texte principal ou description de l'annonce.", null=True, verbose_name="Contenu Textuel de l'Annonce"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_creative_content_text_es',
            field=models.TextField(blank=True, help_text="Texte principal ou description de l'annonce.", null=True, verbose_name="Contenu Textuel de l'Annonce"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_creative_content_text_fr',
            field=models.TextField(blank=True, help_text="Texte principal ou description de l'annonce.", null=True, verbose_name="Contenu Textuel de l'Annonce"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='push_message_en',
            field=models.CharField(blank=True, help_text='Texte court et percutant pour la notification push.', max_length=255, null=True, verbose_name='Message de la notification Push'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='push_message_es',
            field=models.CharField(blank=True, help_text='Texte court et percutant pour la notification push.', max_length=255, null=True, verbose_name='Message de la notification Push'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='push_message_fr',
            field=models.CharField(blank=True, help_text='Texte court et percutant pour la notification push.', max_length=255, null=True, verbose_name='Message de la notification Push'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Titre de l'Annonce/title"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Titre de l'Annonce/title"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Titre de l'Annonce/title"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='reporting_format',
            field=models.CharField(choices=[('PDF', 'pdf'), ('CSV', 'csv'), ('XLSX', 'xlsx'), ('XML', 'xml')], default='PDF', max_length=30, verbose_name='Format de Rapports/reporting_format'),
        ),
    ]
