# Generated by Django 5.2.1 on 2025-06-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tripday',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tripday',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='tripday',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tripday',
            name='address_cache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planners.addresscache'),
        ),
    ]
