# Generated by Django 5.2.1 on 2025-06-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0002_addresscache_remove_tripday_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
