# Generated by Django 5.2.1 on 2025-06-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0003_trip_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
