# Generated by Django 5.2.1 on 2025-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0004_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresscache',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addresscache',
            name='address',
            field=models.CharField(max_length=512),
        ),
    ]
