# Generated by Django 5.2.1 on 2025-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0005_addresscache_place_id_alter_addresscache_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripstep',
            old_name='travel_time_minutes',
            new_name='travel_duration_minutes',
        ),
        migrations.AddField(
            model_name='tripstep',
            name='travel_distance_meters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripstep',
            name='travel_mode',
            field=models.CharField(choices=[('walking', 'Walking'), ('driving', 'Driving'), ('bicycling', 'Bicycling'), ('transit', 'Transit')], default='walking', max_length=20),
        ),
    ]
