# Generated by Django 5.2.1 on 2025-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0006_rename_travel_time_minutes_tripstep_travel_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='adults',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='children',
            field=models.SmallIntegerField(default=0),
        ),
    ]
