# Generated by Django 5.2.1 on 2025-09-09 15:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0007_trip_adults_trip_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresscache',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='addresscache',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='addresscache',
            name='address',
        ),
        migrations.AddField(
            model_name='addresscache',
            name='city',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='components',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='country_code',
            field=models.CharField(db_index=True, default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='formatted_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='last_used_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='refreshed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='source',
            field=models.CharField(default='google', max_length=16),
        ),
        migrations.AddField(
            model_name='addresscache',
            name='state_code',
            field=models.CharField(db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='addresscache',
            name='place_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='tripstep',
            name='end_time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tripstep',
            name='travel_mode',
            field=models.CharField(choices=[('walking', 'Walking'), ('driving', 'Driving'), ('bicycling', 'Bicycling'), ('transit', 'Transit')], default='driving', max_length=20),
        ),
        migrations.AddIndex(
            model_name='addresscache',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='planners_ad_search__13937a_gin'),
        ),
        migrations.AddIndex(
            model_name='addresscache',
            index=models.Index(fields=['language'], name='planners_ad_languag_01fd51_idx'),
        ),
        migrations.AddIndex(
            model_name='addresscache',
            index=models.Index(fields=['city'], name='planners_ad_city_23832d_idx'),
        ),
        migrations.AddIndex(
            model_name='addresscache',
            index=models.Index(fields=['state_code'], name='planners_ad_state_c_932c63_idx'),
        ),
        migrations.AddIndex(
            model_name='addresscache',
            index=models.Index(fields=['country_code'], name='planners_ad_country_315196_idx'),
        ),
    ]
