# Generated by Django 5.2.1 on 2025-12-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0009_my_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscache',
            name='place_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
