# Generated by Django 5.2.1 on 2025-07-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
